# Generated by Django 3.0 on 2020-10-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=150)),
                ('employer', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('package', models.CharField(max_length=150)),
                ('ref_no', models.IntegerField()),
            ],
        ),
    ]
