# Generated by Django 3.0 on 2020-10-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='package',
            field=models.IntegerField(),
        ),
    ]
