# Generated by Django 3.0 on 2020-10-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_auto_20201006_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('1', 'Computer Science'), ('2', 'Electronics and Telecommunication'), ('3', 'Mechanical'), ('4', 'Civil')], default='1', max_length=150),
        ),
    ]
