# Generated by Django 3.1.2 on 2020-11-03 00:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurExptLect2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.CharField(max_length=150, verbose_name='Name of Guest')),
                ('organization', models.CharField(max_length=150, verbose_name='Company/Organization Represented')),
                ('designation', models.CharField(max_length=150)),
                ('topic', models.CharField(max_length=150)),
                ('department', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Electronics and Telecommunication', 'Electronics and Telecommunication'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil')], max_length=250, verbose_name='Name of Organizing Department')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('no_of_part', models.IntegerField(verbose_name='No of Participants')),
            ],
        ),
        migrations.CreateModel(
            name='CurGuestLect1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.CharField(max_length=150, verbose_name='Name of Guest')),
                ('organization', models.CharField(max_length=150, verbose_name='Company/Organization Represented')),
                ('designation', models.CharField(max_length=150)),
                ('topic', models.CharField(max_length=150)),
                ('department', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Electronics and Telecommunication', 'Electronics and Telecommunication'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil')], max_length=150, verbose_name='Name of Organizing Department')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('no_of_part', models.IntegerField(verbose_name='No of Participants')),
            ],
        ),
        migrations.CreateModel(
            name='CurStudSponsor5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title of Project')),
                ('comp_rep', models.CharField(max_length=250, verbose_name='Name of Company Representative')),
                ('comp_sponsor', models.CharField(max_length=250, verbose_name='Name of Sponsoring company')),
                ('from_date', models.DateField(default=datetime.date.today, verbose_name='Duration (From)')),
                ('to_date', models.DateField(default=datetime.date.today, verbose_name='Duration (To)')),
                ('grant', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=150, verbose_name='Grant Received')),
                ('status', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='CurStudTrain3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Electronics and Telecommunication', 'Electronics and Telecommunication'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil')], default='Computer Science', max_length=150)),
                ('student_name', models.CharField(max_length=150, verbose_name='Name of Student')),
                ('company', models.CharField(max_length=250, verbose_name='Name of Company')),
                ('sector', models.CharField(max_length=250)),
                ('from_date', models.DateField(default=datetime.date.today, verbose_name='Duration (From)')),
                ('to_date', models.DateField(default=datetime.date.today, verbose_name='Duration (To)')),
            ],
        ),
        migrations.CreateModel(
            name='CurStudVisit4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Electronics and Telecommunication', 'Electronics and Telecommunication'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil')], default='Computer Science', max_length=150)),
                ('company', models.CharField(max_length=250, verbose_name='Name of Company')),
                ('sector', models.CharField(max_length=250)),
                ('fac_name', models.CharField(max_length=150, verbose_name='Faculty Name')),
                ('no_of_stud', models.IntegerField(verbose_name='No of Students')),
                ('from_date', models.DateField(default=datetime.date.today, verbose_name='Duration (From)')),
                ('to_date', models.DateField(default=datetime.date.today, verbose_name='Duration (To)')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True, verbose_name='Department Name')),
            ],
        ),
        migrations.CreateModel(
            name='DeptEvent1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Electronics and Telecommunication', 'Electronics and Telecommunication'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil')], default='Computer Science', max_length=150)),
                ('event_type', models.CharField(max_length=150, verbose_name='Event Type')),
                ('event_name', models.CharField(max_length=150, verbose_name='Event Name')),
                ('guest_name', models.CharField(max_length=150, verbose_name='Guest Name')),
                ('guest_affl', models.CharField(max_length=250, verbose_name='Affiliation of guest')),
                ('no_of_part', models.IntegerField(verbose_name='No of Participants')),
                ('from_date', models.DateField(default=datetime.date.today, verbose_name='From')),
                ('to_date', models.DateField(default=datetime.date.today, verbose_name='To')),
            ],
        ),
        migrations.CreateModel(
            name='DeptEvent2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_name', models.CharField(max_length=150, verbose_name='Activity Name')),
                ('school', models.CharField(max_length=150)),
                ('school_cont', models.CharField(max_length=250, verbose_name='School Contact Details')),
                ('fac_name', models.CharField(max_length=250, verbose_name='Faculty Name')),
                ('part_no', models.IntegerField(verbose_name='No of Participants')),
                ('from_date', models.DateField(default=datetime.date.today, verbose_name='From')),
                ('to_date', models.DateField(default=datetime.date.today, verbose_name='To')),
            ],
        ),
        migrations.CreateModel(
            name='DeptFacultyDev4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Electronics and Telecommunication', 'Electronics and Telecommunication'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil')], default='Computer Science', max_length=150)),
                ('program', models.CharField(max_length=150)),
                ('agency', models.CharField(max_length=150)),
                ('amm_sponsored', models.IntegerField(default=0)),
                ('from_date', models.DateField(default=datetime.date.today, verbose_name='From')),
                ('to_date', models.DateField(default=datetime.date.today, verbose_name='To')),
                ('no_of_part', models.IntegerField(verbose_name='No of Participants')),
                ('level', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='DeptProEvent3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Electronics and Telecommunication', 'Electronics and Telecommunication'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil')], default='Computer Science', max_length=150)),
                ('activity', models.CharField(max_length=150)),
                ('resourse_person', models.CharField(max_length=150)),
                ('resourse_person_contact', models.IntegerField()),
                ('no_of_part', models.IntegerField(verbose_name='No of Participants')),
                ('from_date', models.DateField(default=datetime.date.today, verbose_name='From')),
                ('to_date', models.DateField(default=datetime.date.today, verbose_name='To')),
            ],
        ),
        migrations.CreateModel(
            name='DeptStartUp6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_name', models.CharField(max_length=150)),
                ('startup_nature', models.CharField(max_length=150)),
                ('start_date', models.CharField(max_length=150, verbose_name='Commencement Date')),
                ('founder', models.CharField(max_length=150)),
                ('LLP_no', models.IntegerField(verbose_name='LLP number')),
                ('website', models.CharField(max_length=150)),
                ('team_members', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DeptStudPart5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Electronics and Telecommunication', 'Electronics and Telecommunication'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil')], default='Computer Science', max_length=150)),
                ('student_name', models.CharField(max_length=150)),
                ('event_type', models.CharField(max_length=150)),
                ('event_name', models.CharField(max_length=150)),
                ('org_inst', models.CharField(max_length=264)),
                ('from_date', models.DateField(default=datetime.date.today, verbose_name='From')),
                ('to_date', models.DateField(default=datetime.date.today, verbose_name='To')),
                ('no_of_part', models.IntegerField(verbose_name='No of Participants')),
                ('level', models.CharField(max_length=150)),
                ('awards', models.CharField(max_length=264, verbose_name='Recognition Awards')),
            ],
        ),
        migrations.CreateModel(
            name='FacAchieve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fac_name', models.CharField(max_length=150, verbose_name='Faculty Name')),
                ('department', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Electronics and Telecommunication', 'Electronics and Telecommunication'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil')], default='Computer Science', max_length=150)),
                ('achievement', models.CharField(max_length=150)),
                ('level', models.CharField(max_length=150)),
                ('dates', models.DateField(default=datetime.date.today, verbose_name='Dates')),
            ],
        ),
        migrations.CreateModel(
            name='FacBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('author_name', models.CharField(max_length=150, verbose_name='Name of author(s)')),
                ('publication', models.CharField(max_length=150, verbose_name='Publication')),
                ('ISBN', models.IntegerField(verbose_name='ISBN number')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Electronics and Telecommunication', 'Electronics and Telecommunication'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil')], default='Computer Science', max_length=150)),
                ('Class', models.CharField(choices=[('', 'Choose...'), ('SE', 'SE'), ('TE', 'TE'), ('BE', 'BE')], default='', max_length=150)),
                ('exam_type', models.CharField(choices=[('', 'Choose...'), ('MID SEM', 'MID SEM'), ('PRELIMS', 'PRELIMS'), ('END SEM', 'END SEM')], default='', max_length=150)),
                ('subject', models.CharField(choices=[('', 'Choose...'), ('COMPUTER SUBJECTS', (('DBMS', 'DBMS'), ('TOC', 'TOC'), ('CN', 'CN'), ('SEMP', 'SEMP'), ('ISEE', 'ISEE'))), ('ENTC SUBJECTS', (('ENTC1', 'ENTC1'), ('ENTC2', 'ENTC2'), ('ENTC3', 'ENTC3'), ('ENTC4', 'ENTC4'), ('ENTC5', 'ENTC5'))), ('MECHANICAL SUBJECTS', (('MECH1', 'MECH1'), ('MECH1', 'MECH1'), ('MECH1', 'MECH1'), ('MECH1', 'MECH1'), ('MECH1', 'MECH1'))), ('CIVIL SUBJECTS', (('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('C4', 'C4'), ('C5', 'C5'))), ('ENGINEERING SCIENCE SUBJECTS', (('PHYSICS', 'PHYSICS'), ('MATHS', 'MATHS'), ('CHEMISTRY', 'CHEMISTRY'), ('ELECTRONICS', 'ELECTRONICS'), ('ELECTRICAL', 'ELECTRICAL'), ('GRAPHICS', 'GRAPHICS'), ('MECHANICS', 'MECHANICS')))], default='', max_length=150)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Exam Date')),
                ('appeared', models.IntegerField()),
                ('passed', models.IntegerField()),
                ('perct', models.IntegerField(default=0, verbose_name='Percentage')),
            ],
        ),
        migrations.CreateModel(
            name='IndInst5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_board', models.CharField(max_length=150, verbose_name='Type of Board/Council')),
                ('name_of_industry_member', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=150)),
                ('name_of_company', models.CharField(max_length=256)),
                ('tenure', models.CharField(max_length=100)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.sector')),
            ],
        ),
        migrations.CreateModel(
            name='IndInst4Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_faculty', models.CharField(max_length=150)),
                ('name_of_company', models.CharField(max_length=256)),
                ('date_of_appointment', models.DateField(default=datetime.date.today)),
                ('type_of_board', models.CharField(max_length=150, verbose_name='Type of Board/Council')),
                ('designation_of_faculty', models.CharField(max_length=150)),
                ('meeting_date', models.DateField(blank=True, verbose_name='Meeting Date(if any)')),
                ('department', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='department.department')),
            ],
        ),
        migrations.CreateModel(
            name='IndInst3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_faculty', models.CharField(max_length=150)),
                ('name_of_company', models.CharField(max_length=256)),
                ('title_of_training', models.CharField(max_length=256)),
                ('from_date', models.DateField(default=datetime.date.today, verbose_name='Dates (From)')),
                ('to_date', models.DateField(default=datetime.date.today, verbose_name='Dates (To)')),
                ('outcome', models.TextField()),
                ('department', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='department.department')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.sector')),
            ],
        ),
        migrations.CreateModel(
            name='IndInst2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_faculty', models.CharField(max_length=150)),
                ('name_of_company', models.CharField(max_length=256)),
                ('title_of_training', models.CharField(max_length=256)),
                ('from_date', models.DateField(default=datetime.date.today, verbose_name='Dates (From)')),
                ('to_date', models.DateField(default=datetime.date.today, verbose_name='Dates (To)')),
                ('outcome', models.TextField()),
                ('department', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='department.department')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.sector')),
            ],
        ),
        migrations.CreateModel(
            name='IndFacvisit1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=256, verbose_name='Name of Company')),
                ('purpose', models.TextField()),
                ('from_date', models.DateField(default=datetime.date.today, verbose_name='Dates (From)')),
                ('to_date', models.DateField(default=datetime.date.today, verbose_name='Dates (To)')),
                ('outcome', models.TextField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.sector')),
            ],
        ),
    ]
