# Generated by Django 3.1.2 on 2021-01-11 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resinternational3',
            old_name='approval',
            new_name='approvals',
        ),
        migrations.RenameField(
            model_name='resinternational3',
            old_name='volume_Issue',
            new_name='volume_Issue_ICV',
        ),
    ]
