# Generated by Django 3.1.2 on 2020-10-16 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacAchieve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fac_name', models.CharField(max_length=150, verbose_name='Faculty Name')),
                ('department', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Electronics and Telecommunication', 'Electronics and Telecommunication'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil')], default='Computer Science', max_length=150)),
                ('achievement', models.CharField(max_length=150)),
                ('level', models.CharField(max_length=150)),
                ('dates', models.DateField(default=datetime.date.today, verbose_name='Dates')),
            ],
        ),
    ]
