# Generated by Django 3.1.2 on 2020-10-13 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deptstartup6',
            name='date_commencement',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
