# Generated by Django 3.1.2 on 2020-11-03 14:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndInst7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_project', models.CharField(max_length=150)),
                ('name_of_coordinator', models.CharField(max_length=150)),
                ('name_of_sponsoring_company', models.CharField(max_length=150)),
                ('duration_from', models.DateField(default=datetime.date.today, verbose_name='Duration(From)')),
                ('duration_to', models.DateField(default=datetime.date.today, verbose_name='Duration(To)')),
                ('grant_received', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=150)),
                ('status_of_project', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='IndInst8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_faculty', models.CharField(max_length=150)),
                ('name_of_company', models.CharField(max_length=256, verbose_name='Name of Company/ organization')),
                ('title_of_project', models.CharField(max_length=150)),
                ('revenue_generated', models.IntegerField()),
                ('dates_from', models.DateField(default=datetime.date.today, verbose_name='Dates (From)')),
                ('dates_to', models.DateField(default=datetime.date.today, verbose_name='Dates (To)')),
                ('status_of_project', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='IndInst9',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_faculty_coordinator', models.CharField(max_length=150)),
                ('name_of_company', models.CharField(max_length=256, verbose_name='Name of Company/ organization')),
                ('date_of_MOU', models.DateField(default=datetime.date.today)),
                ('purpose_of_MOU', models.TextField()),
                ('department', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='department.department')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.sector')),
            ],
        ),
        migrations.CreateModel(
            name='IndInst6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_faculty', models.CharField(max_length=150)),
                ('title_of_invention', models.CharField(max_length=150)),
                ('patent_no', models.CharField(max_length=150)),
                ('date_of_grant', models.DateField(default=datetime.date.today, verbose_name='Date of Grant/File')),
                ('name_of_company', models.CharField(max_length=256)),
                ('date_of_adoption', models.DateField(default=datetime.date.today)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.sector')),
            ],
        ),
    ]
