# Generated by Django 3.1.2 on 2021-03-01 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(default='Computer Science', on_delete=django.db.models.deletion.CASCADE, to='department.department'),
        ),
    ]
