# Generated by Django 3.1.2 on 2021-03-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='new_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Address'),
        ),
    ]
