# Generated by Django 3.1.2 on 2020-10-11 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeptFacDevelopment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150)),
                ('event_type', models.CharField(max_length=150)),
                ('event_name', models.CharField(max_length=150)),
                ('org_inst', models.CharField(max_length=264)),
                ('from_date', models.DateField(default=datetime.date.today, verbose_name='From')),
                ('to_date', models.DateField(default=datetime.date.today, verbose_name='To')),
                ('no_of_part', models.IntegerField(verbose_name='No of Participants')),
                ('level', models.CharField(max_length=150)),
            ],
        ),
    ]
