# Generated by Django 3.1.2 on 2020-11-05 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudFac1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_or_division', models.CharField(max_length=150)),
                ('type_of_meeting_open_GFM_or_HOD_close', models.CharField(max_length=150)),
                ('name_of_faculty', models.CharField(max_length=150)),
                ('type_of_mentoring', models.CharField(max_length=150)),
                ('dates_of_mentoring_activity', models.CharField(max_length=150)),
                ('department', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='department.department')),
            ],
        ),
    ]
