# Generated by Django 3.1.2 on 2021-03-08 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_userprofile_new_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='new_email',
        ),
    ]
