# Generated by Django 3.1.2 on 2021-01-11 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_auto_20210111_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resinternational3',
            old_name='approvals',
            new_name='approval',
        ),
        migrations.RenameField(
            model_name='resnational4',
            old_name='volume_Issue',
            new_name='volume_Issue_ICV',
        ),
    ]
