# Generated by Django 3.1.2 on 2021-03-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_profile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='profile_images/default_profile_image.jpg', upload_to='profile_images/'),
        ),
    ]
