# Generated by Django 3.1.2 on 2021-02-05 18:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_ecellcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_company', models.CharField(max_length=150)),
                ('sector', models.CharField(max_length=150)),
                ('discipline', models.CharField(max_length=150)),
                ('dates_of_drive', models.CharField(max_length=150)),
                ('no_of_eligible_students', models.PositiveIntegerField()),
                ('no_of_students_offered_jobs', models.PositiveIntegerField()),
                ('package', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Placement3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_company', models.CharField(max_length=150)),
                ('sector', models.CharField(max_length=150)),
                ('location_open_College_or_Industry_close', models.CharField(max_length=200)),
                ('date_of_walk_in', models.DateField(default=datetime.date.today, verbose_name='Date of Walk-In')),
                ('no_of_students_appeared', models.PositiveIntegerField()),
                ('no_of_students_offered_jobs', models.PositiveIntegerField()),
                ('package', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Placement5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_student', models.CharField(max_length=150)),
                ('discipline', models.CharField(max_length=150)),
                ('type_of_self_employment', models.CharField(choices=[('Start up', 'Start up'), ('NGO', 'NGO')], max_length=150)),
                ('name_of_firm_or_company', models.CharField(max_length=150, verbose_name='Name of Firm/ Company')),
                ('products_or_services_offered', models.CharField(max_length=150, verbose_name='Products/ Services offered')),
            ],
        ),
        migrations.CreateModel(
            name='Placement4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_student', models.CharField(max_length=150)),
                ('name_of_employer', models.CharField(max_length=150)),
                ('date_of_selection', models.DateField(default=datetime.date.today, verbose_name='Date of Selection')),
                ('package', models.PositiveIntegerField()),
                ('appointment_reference_no', models.CharField(max_length=150)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
            ],
        ),
    ]
