# Generated by Django 3.1.2 on 2020-10-16 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_facachieve'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurStudTrain3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Electronics and Telecommunication', 'Electronics and Telecommunication'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil')], default='Computer Science', max_length=150)),
                ('student_name', models.CharField(max_length=150, verbose_name='Name of Student')),
                ('company', models.CharField(max_length=250, verbose_name='Name of Company')),
                ('sector', models.CharField(max_length=250)),
                ('from_date', models.DateField(default=datetime.date.today, verbose_name='Date (From)')),
                ('to_date', models.DateField(default=datetime.date.today, verbose_name='Date (To)')),
            ],
        ),
    ]
