# Generated by Django 3.1.2 on 2020-10-13 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_auto_20201013_1418'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeptStudPart',
            new_name='DeptStudPart5',
        ),
    ]
