# Generated by Django 3.1.2 on 2020-11-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_indinst6_indinst7_indinst8_indinst9'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indinst9',
            name='sector',
            field=models.CharField(choices=[('Agriculture', 'Agriculture'), ('Banking', 'Banking'), ('Construction', 'Construction'), ('Consumer durables', 'Consumer durables'), ('Engineering', 'Engineering'), ('Health care', 'Health care')], max_length=150),
        ),
    ]
