# Generated by Django 3.1.2 on 2021-03-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.TextField(blank=True, choices=[('Non-Teaching', 'Non-Teaching'), ('Computer Science', 'Computer Science'), ('Electronics and Telecommunication', 'Electronics and Telecommunication'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
