# Generated by Django 2.2.16 on 2020-10-12 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_auto_20201011_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyDevProOrg_Dep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=150)),
                ('department_name', models.CharField(max_length=150)),
                ('sponsoring_agency', models.CharField(max_length=150)),
                ('amm_sponsored', models.IntegerField(default=0)),
                ('from_date', models.DateField(default=datetime.date.today, verbose_name='From')),
                ('to_date', models.DateField(default=datetime.date.today, verbose_name='To')),
                ('no_of_part', models.IntegerField(verbose_name='No of Participants')),
                ('level', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='StartUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_name', models.CharField(max_length=150)),
                ('nature_startup', models.CharField(max_length=150)),
                ('date_commencement', models.CharField(max_length=150)),
                ('Founder', models.CharField(max_length=150)),
                ('LLP_no', models.IntegerField()),
                ('startup_web', models.CharField(max_length=150)),
                ('team_members', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='year_admission',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='year_down',
            field=models.IntegerField(default=0),
        ),
    ]
