# Generated by Django 3.1.2 on 2020-11-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_auto_20201103_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indinst9',
            name='sector',
            field=models.CharField(choices=[('Agriculture', 'Agriculture'), ('Banking', 'Banking'), ('Construction', 'Construction'), ('Consumer durables', 'Consumer durables'), ('Engineering', 'Engineering'), ('Health care', 'Health care'), ('IT', 'IT')], max_length=150),
        ),
    ]
