# Generated by Django 3.1.2 on 2020-10-13 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_auto_20201013_1428'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FacultyDevProOrg_Dep',
            new_name='DeptFacDevProg4',
        ),
        migrations.RenameField(
            model_name='deptfacdevprog4',
            old_name='amm_sponsored',
            new_name='amt_sponsored',
        ),
    ]
