# Generated by Django 3.1.2 on 2020-10-16 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_curstudtrain3'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurStudVisit4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Electronics and Telecommunication', 'Electronics and Telecommunication'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil')], default='Computer Science', max_length=150)),
                ('company', models.CharField(max_length=250, verbose_name='Name of Company')),
                ('sector', models.CharField(max_length=250)),
                ('fac_name', models.CharField(max_length=150)),
                ('no_of_stud', models.IntegerField()),
                ('from_date', models.DateField(default=datetime.date.today, verbose_name='Duration (From)')),
                ('to_date', models.DateField(default=datetime.date.today, verbose_name='Duration (To)')),
            ],
        ),
        migrations.AlterField(
            model_name='curstudtrain3',
            name='from_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Duration (From)'),
        ),
        migrations.AlterField(
            model_name='curstudtrain3',
            name='to_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Duration (To)'),
        ),
    ]
