# Generated by Django 3.1.2 on 2021-03-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_remove_userprofile_new_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
