# Generated by Django 3.1.2 on 2020-11-06 15:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_auto_20201105_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudFac2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_or_division', models.CharField(max_length=150)),
                ('type_of_self_learning_facility', models.CharField(choices=[('Webinars', 'Webinars'), ('Podcast', 'Podcast'), ('MOOC’s', 'MOOC’s'), ('NPTEL courses', 'NPTEL courses'), ('Myexamo', 'Myexamo'), ('Others', 'Others')], default=1, max_length=150)),
                ('name_of_subject', models.CharField(max_length=150)),
                ('no_of_student_participated', models.PositiveIntegerField()),
                ('dates', models.CharField(max_length=150)),
                ('certificate_or_award_received_by_students', models.CharField(blank=True, max_length=150, verbose_name='Certificate/Award Received by students (if any)')),
            ],
        ),
        migrations.CreateModel(
            name='StudFac4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_activity', models.CharField(choices=[('Soft Skill Development', 'Soft Skill Development'), ('Remedial Coaching', 'Remedial Coaching'), ('Language Lab', 'Language Lab'), ('Yoga', 'Yoga'), ('Meditation', 'Meditation'), ('Personal Counseling', 'Personal Counseling'), ('Bridge Courses', 'Bridge Courses'), ('Competitive Examination', 'Competitive Examination'), ('Higher', 'Higher')], default=1, max_length=150)),
                ('date_of_implementation', models.DateField(default=datetime.date.today)),
                ('no_of_students_enrolled', models.PositiveIntegerField()),
                ('agencies_involved', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='StudFac5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_the_professional_development_program', models.CharField(max_length=150)),
                ('organized_for_faculty_or_staff', models.CharField(max_length=150, verbose_name='Organized for Faculty/Staff')),
                ('duration_open_from_close', models.DateField(default=datetime.date.today, verbose_name='Duration (From)')),
                ('duration_open_to_close', models.DateField(default=datetime.date.today, verbose_name='Duration (To)')),
                ('no_of_participants', models.PositiveIntegerField()),
                ('agencies_involved', models.CharField(max_length=250)),
                ('organizing_department', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='department.department')),
            ],
        ),
        migrations.CreateModel(
            name='StudFac3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_student', models.CharField(max_length=150)),
                ('name_of_competitive_exam_appeard_or_qualified', models.CharField(choices=[('MPSC', 'MPSC'), ('UPSC', 'UPSC'), ('GATE', 'GATE'), ('GRE', 'GRE'), ('IELTS', 'IELTS'), ('TOEFL', 'TOEFL'), ('CAT', 'CAT'), ('Others', 'Others')], default=1, max_length=150)),
                ('competitive_exam_seat_no', models.CharField(max_length=150)),
                ('score', models.FloatField()),
                ('department', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='department.department')),
            ],
        ),
    ]
