# Generated by Django 3.1.2 on 2021-01-13 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_auto_20210111_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfInternational5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title of the paper')),
                ('department', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Electronics and Telecommunication', 'Electronics and Telecommunication'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil')], default='Computer Science', max_length=150)),
                ('authors_Name', models.CharField(max_length=150, null=True)),
                ('conference_Name', models.CharField(max_length=150, null=True)),
                ('oraganised_by', models.CharField(max_length=150, null=True)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('amount', models.IntegerField(default=0, verbose_name='Amount (if paid by institute)')),
                ('location', models.CharField(max_length=150, null=True)),
                ('url', models.URLField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfNational6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title of the paper')),
                ('department', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Electronics and Telecommunication', 'Electronics and Telecommunication'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil')], default='Computer Science', max_length=150)),
                ('authors_Name', models.CharField(max_length=150)),
                ('conference_Name', models.CharField(max_length=150)),
                ('oraganised_by', models.CharField(max_length=150)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('amount', models.IntegerField(default=0, verbose_name='Amount (if paid by institute)')),
                ('location', models.CharField(max_length=150)),
                ('url', models.URLField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacEvents8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_Type', models.CharField(max_length=150)),
                ('event_Name', models.CharField(max_length=150)),
                ('name_of_Faculty', models.CharField(max_length=150)),
                ('department', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Electronics and Telecommunication', 'Electronics and Telecommunication'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil')], default='Computer Science', max_length=150)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('level', models.IntegerField()),
                ('amount', models.IntegerField(default=0)),
                ('organising_Institute', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='FacPatents10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_Name', models.CharField(max_length=150)),
                ('department', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Electronics and Telecommunication', 'Electronics and Telecommunication'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil')], default='Computer Science', max_length=150)),
                ('invention_Title', models.CharField(max_length=150, verbose_name='Title of Invention')),
                ('patent_Number', models.CharField(max_length=150, verbose_name='Patent/Application Number')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('patent_Status', models.CharField(max_length=150, verbose_name='Current Status of Patent')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalPrac9',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_Name', models.CharField(max_length=150)),
                ('department', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Electronics and Telecommunication', 'Electronics and Telecommunication'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil')], default='Computer Science', max_length=150)),
                ('professional_Practice_Type', models.CharField(max_length=150, verbose_name='Type of professional practices')),
                ('designation', models.CharField(max_length=150, verbose_name='Designation in Professional Practices')),
                ('organising_Institute', models.CharField(max_length=150)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='ResIndustrial7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title of the paper')),
                ('authors_Name', models.CharField(max_length=150)),
                ('co_Author_Name', models.CharField(max_length=150)),
                ('name_of_Company', models.CharField(max_length=150)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('name_of_Conference_orjournal', models.CharField(max_length=150, verbose_name='Name of Conference/Details of Journal')),
                ('location', models.CharField(max_length=150)),
                ('url', models.URLField(max_length=150, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='resnational4',
            old_name='date_of_publication',
            new_name='date_of_Publication',
        ),
        migrations.AlterField(
            model_name='indfacvisit1',
            name='purpose',
            field=models.TextField(max_length=256, verbose_name='Purpose of Visit'),
        ),
        migrations.AlterField(
            model_name='resfunds2',
            name='grants_recieved',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resfunds2',
            name='grants_utilized',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resfunds2',
            name='remaining_grant',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resinternational3',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Amount (if paid by institute)'),
        ),
        migrations.AlterField(
            model_name='resnational4',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Amount (if paid by institute)'),
        ),
        migrations.AlterField(
            model_name='resnational4',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Title of the paper'),
        ),
    ]
