# Generated by Django 3.1.2 on 2021-02-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_placement1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement1',
            name='year',
            field=models.IntegerField(choices=[(2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], default=2021, unique=True, verbose_name='year'),
        ),
    ]
