# Generated by Django 3.1.2 on 2020-10-16 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_auto_20201016_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurStudSponsor5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title of Project')),
                ('comp_rep', models.CharField(max_length=250, verbose_name='Name of Company Representative')),
                ('comp_sponsor', models.CharField(max_length=250, verbose_name='Name of Sponsoring company')),
                ('from_date', models.DateField(default=datetime.date.today, verbose_name='Duration (From)')),
                ('to_date', models.DateField(default=datetime.date.today, verbose_name='Duration (To)')),
                ('grant', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='no', max_length=150, verbose_name='Grant Received')),
                ('status', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='curstudvisit4',
            name='fac_name',
            field=models.CharField(max_length=150, verbose_name='Faculty Name'),
        ),
        migrations.AlterField(
            model_name='curstudvisit4',
            name='no_of_stud',
            field=models.IntegerField(verbose_name='No of Students'),
        ),
    ]
