# Generated by Django 3.1.2 on 2021-03-08 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_auto_20210307_2033'),
        ('department', '0004_studentresult_created_by'),
    ]

    operations = [
    ]
