# Generated by Django 3.1.2 on 2020-10-13 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_auto_20201013_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeptEvent2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_name', models.CharField(max_length=150)),
                ('school', models.CharField(max_length=150)),
                ('school_cont', models.CharField(max_length=250)),
                ('fac_name', models.CharField(max_length=250)),
                ('part_no', models.IntegerField()),
                ('from_date', models.DateField(default=datetime.date.today, verbose_name='From')),
                ('to_date', models.DateField(default=datetime.date.today, verbose_name='To')),
            ],
        ),
    ]
