# Generated by Django 3.1.2 on 2020-11-06 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_studfac2_studfac3_studfac4_studfac5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studfac5',
            name='duration_open_from_close',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Duration (From)'),
        ),
        migrations.AlterField(
            model_name='studfac5',
            name='duration_open_to_close',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Duration (To)'),
        ),
    ]
