# Generated by Django 3.1.2 on 2021-01-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0005_auto_20210117_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='percentage',
            field=models.FloatField(default=0, verbose_name='Percentage'),
        ),
    ]
