# Generated by Django 3.1.2 on 2020-11-06 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0005_auto_20201106_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studfac5',
            name='duration_open_from_close',
            field=models.DateField(default=datetime.date.today, verbose_name='Duration (From)'),
        ),
        migrations.AlterField(
            model_name='studfac5',
            name='duration_open_to_close',
            field=models.DateField(default=datetime.date.today, verbose_name='Duration (To)'),
        ),
    ]
