# Generated by Django 3.1.2 on 2021-02-24 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0005_auto_20210222_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=250)),
                ('civil', models.PositiveIntegerField(default=1)),
                ('computer', models.PositiveIntegerField(default=10)),
                ('E_andTC', models.PositiveIntegerField(default=10)),
                ('mechanical', models.PositiveIntegerField(default=10)),
                ('first_Year', models.PositiveIntegerField(default=10)),
                ('total', models.PositiveIntegerField(default=10)),
            ],
        ),
    ]
