# Generated by Django 3.1.2 on 2020-10-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0005_auto_20201016_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curstudsponsor5',
            name='grant',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=150, verbose_name='Grant Received'),
        ),
    ]
