# Generated by Django 3.1.2 on 2021-03-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0005_auto_20210301_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='profile_images/default_profile_image.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
