# Generated by Django 3.1.2 on 2021-03-09 10:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0005_merge_20210308_2115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deptevent1',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
        migrations.AddField(
            model_name='deptevent1',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deptevent1',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='library1',
            name='year',
            field=models.IntegerField(choices=[(2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], default=2021, unique_for_year=True, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='library2',
            name='details',
            field=models.CharField(choices=[('', 'Choose...'), ('Number of Faculties Visited', 'Number of Faculties Visited'), ('Number of Students Visited', 'Number of Students Visited'), ('Number of Faculty Transctions', 'Number of Faculty Transctions'), ('Number of Student Transactions', 'Number of Student Transactions')], default='', max_length=250),
        ),
    ]
