# Generated by Django 3.1.2 on 2021-02-24 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0006_library2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
