# Generated by Django 3.1.2 on 2021-03-09 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0006_auto_20210309_1029'),
        ('department', '0006_auto_20210309_0848'),
    ]

    operations = [
    ]
