# Generated by Django 3.0 on 2020-10-17 00:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0006_auto_20201016_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurExptLect2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.CharField(max_length=150, verbose_name='Name of Guest')),
                ('organization', models.CharField(max_length=150, verbose_name='Company/Organization Represented')),
                ('designation', models.CharField(max_length=150)),
                ('topic', models.CharField(max_length=150)),
                ('department', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Electronics and Telecommunication', 'Electronics and Telecommunication'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil')], max_length=250, verbose_name='Name of Organizing Department')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('no_of_part', models.IntegerField(verbose_name='No of Participants')),
            ],
        ),
        migrations.CreateModel(
            name='CurGuestLect1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.CharField(max_length=150, verbose_name='Name of Guest')),
                ('organization', models.CharField(max_length=150, verbose_name='Company/Organization Represented')),
                ('designation', models.CharField(max_length=150)),
                ('topic', models.CharField(max_length=150)),
                ('department', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Electronics and Telecommunication', 'Electronics and Telecommunication'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil')], max_length=150, verbose_name='Name of Organizing Department')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('no_of_part', models.IntegerField(verbose_name='No of Participants')),
            ],
        ),
        migrations.CreateModel(
            name='FacBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('author_name', models.CharField(max_length=150, verbose_name='Name of author(s)')),
                ('publication', models.CharField(max_length=150, verbose_name='Publication')),
                ('ISBN', models.IntegerField(verbose_name='ISBN number')),
            ],
        ),
    ]
