# Generated by Django 3.1.2 on 2020-11-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0006_auto_20201106_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indfacvisit1',
            name='sector',
            field=models.CharField(choices=[('Agriculture', 'Agriculture'), ('Banking', 'Banking'), ('Construction', 'Construction'), ('Consumer durables', 'Consumer durables'), ('Engineering', 'Engineering'), ('Health care', 'Health care'), ('IT', 'IT'), ('Metal and mining', 'Metal and mining'), ('Oil and Gas', 'Oil and Gas'), ('Power', 'Power'), ('Retail', 'Retail'), ('Service', 'Service'), ('Transport', 'Transport'), ('others', 'others')], max_length=150),
        ),
        migrations.AlterField(
            model_name='indinst2',
            name='sector',
            field=models.CharField(choices=[('Agriculture', 'Agriculture'), ('Banking', 'Banking'), ('Construction', 'Construction'), ('Consumer durables', 'Consumer durables'), ('Engineering', 'Engineering'), ('Health care', 'Health care'), ('IT', 'IT'), ('Metal and mining', 'Metal and mining'), ('Oil and Gas', 'Oil and Gas'), ('Power', 'Power'), ('Retail', 'Retail'), ('Service', 'Service'), ('Transport', 'Transport'), ('others', 'others')], max_length=150),
        ),
        migrations.AlterField(
            model_name='indinst3',
            name='sector',
            field=models.CharField(choices=[('Agriculture', 'Agriculture'), ('Banking', 'Banking'), ('Construction', 'Construction'), ('Consumer durables', 'Consumer durables'), ('Engineering', 'Engineering'), ('Health care', 'Health care'), ('IT', 'IT'), ('Metal and mining', 'Metal and mining'), ('Oil and Gas', 'Oil and Gas'), ('Power', 'Power'), ('Retail', 'Retail'), ('Service', 'Service'), ('Transport', 'Transport'), ('others', 'others')], max_length=150),
        ),
        migrations.AlterField(
            model_name='indinst5',
            name='sector',
            field=models.CharField(choices=[('Agriculture', 'Agriculture'), ('Banking', 'Banking'), ('Construction', 'Construction'), ('Consumer durables', 'Consumer durables'), ('Engineering', 'Engineering'), ('Health care', 'Health care'), ('IT', 'IT'), ('Metal and mining', 'Metal and mining'), ('Oil and Gas', 'Oil and Gas'), ('Power', 'Power'), ('Retail', 'Retail'), ('Service', 'Service'), ('Transport', 'Transport'), ('others', 'others')], max_length=150),
        ),
        migrations.AlterField(
            model_name='indinst6',
            name='sector',
            field=models.CharField(choices=[('Agriculture', 'Agriculture'), ('Banking', 'Banking'), ('Construction', 'Construction'), ('Consumer durables', 'Consumer durables'), ('Engineering', 'Engineering'), ('Health care', 'Health care'), ('IT', 'IT'), ('Metal and mining', 'Metal and mining'), ('Oil and Gas', 'Oil and Gas'), ('Power', 'Power'), ('Retail', 'Retail'), ('Service', 'Service'), ('Transport', 'Transport'), ('others', 'others')], max_length=150),
        ),
        migrations.DeleteModel(
            name='Sector',
        ),
    ]
