# Generated by Django 3.1.2 on 2021-03-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0007_merge_20210309_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='centersact5',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='confinternational5',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='confnational6',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='culturalact3',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='culturalcount3',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='curexptlect2',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='curguestlect1',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='curstudsponsor5',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='curstudtrain3',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='curstudvisit4',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='deptevent1',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='deptevent2',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='deptfacultydev4',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='deptproevent3',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='deptstartup6',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='deptstudpart5',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='ecell',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='ecellcount',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='extraact6',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='extracurr1',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='extracurr2',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='facachieve',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='facbook',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='facevents8',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='facpatents10',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='indfacvisit1',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='indinst2',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='indinst3',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='indinst4',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='indinst5',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='indinst6',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='indinst7',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='indinst8',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='indinst9',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='internationalattend12',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='library1',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='library2',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='nationalattend11',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='placement1',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='placement2',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='placement3',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='placement4',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='placement5',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='professionalprac9',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='resfunds2',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='resindustrial7',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='resinternational3',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='resnational4',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='resproject1',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='socialact4',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='studfac1',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='studfac2',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='studfac3',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='studfac4',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='studfac5',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
