# Generated by Django 3.1.2 on 2020-10-28 19:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0007_curexptlect2_curguestlect1_facbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.CharField(max_length=128, primary_key=True, serialize=False, unique=True, verbose_name='Department Name'),
        ),
        migrations.CreateModel(
            name='IndFacvisit1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=256, verbose_name='Name of Company')),
                ('sector', models.CharField(max_length=256)),
                ('purpose', models.TextField()),
                ('from_date', models.DateField(default=datetime.date.today, verbose_name='Dates (From)')),
                ('to_date', models.DateField(default=datetime.date.today, verbose_name='Dates (To)')),
                ('outcome', models.TextField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
            ],
        ),
    ]
