# Generated by Django 3.1.2 on 2021-03-01 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0007_library1'),
    ]

    operations = [
        migrations.AddField(
            model_name='library1',
            name='books_Added_This_Month',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of Books added This Month'),
        ),
        migrations.AddField(
            model_name='library1',
            name='current_Periodicals',
            field=models.PositiveIntegerField(default=0, verbose_name='Current Periodicals'),
        ),
        migrations.AddField(
            model_name='library1',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default=3, max_length=150, verbose_name='Month'),
        ),
        migrations.AddField(
            model_name='library1',
            name='new_Books_Cost',
            field=models.PositiveIntegerField(default=0, verbose_name='Cost spent on new books This Month (Rs.)'),
        ),
        migrations.AddField(
            model_name='library1',
            name='number_of_International_Journals',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of International Journals'),
        ),
        migrations.AddField(
            model_name='library1',
            name='number_of_National_Journals',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of National Journals'),
        ),
        migrations.AddField(
            model_name='library1',
            name='number_of_Volumes',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of Volumes'),
        ),
        migrations.AddField(
            model_name='library1',
            name='thesis_and_Dissertations',
            field=models.PositiveIntegerField(default=0, verbose_name='Thesis & Dissertations'),
        ),
        migrations.AddField(
            model_name='library1',
            name='total_Books',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Number of Books'),
        ),
        migrations.AddField(
            model_name='library1',
            name='video_Recordings_open_NPTEL_or_DMS_close',
            field=models.PositiveIntegerField(default=0, verbose_name='Video Recordings (NPTEL/DMS)'),
        ),
        migrations.AddField(
            model_name='library1',
            name='year',
            field=models.IntegerField(choices=[(2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], default=2021, verbose_name='Year'),
        ),
        migrations.AddField(
            model_name='library2',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='January', max_length=150, verbose_name='Month'),
        ),
        migrations.AddField(
            model_name='library2',
            name='year',
            field=models.IntegerField(choices=[(2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], default=2021, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='library2',
            name='civil',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='placement1',
            name='students_Placed_Percentage',
            field=models.PositiveIntegerField(verbose_name='Percentage of students placed'),
        ),
    ]
