# Generated by Django 3.1.2 on 2021-03-01 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0007_auto_20210301_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='img',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='img',
        ),
    ]
