# Generated by Django 3.1.2 on 2020-11-02 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0008_auto_20201028_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='subject',
            field=models.CharField(choices=[('', 'Choose...'), ('COMPUTER SUBJECTS', (('DBMS', 'DBMS'), ('TOC', 'TOC'), ('CN', 'CN'), ('SEMP', 'SEMP'), ('ISEE', 'ISEE'))), ('ENTC SUBJECTS', (('ENTC1', 'ENTC1'), ('ENTC2', 'ENTC2'), ('ENTC3', 'ENTC3'), ('ENTC4', 'ENTC4'), ('ENTC5', 'ENTC5'))), ('MECHANICAL SUBJECTS', (('MECH1', 'MECH1'), ('MECH1', 'MECH1'), ('MECH1', 'MECH1'), ('MECH1', 'MECH1'), ('MECH1', 'MECH1'))), ('CIVIL SUBJECTS', (('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('C4', 'C4'), ('C5', 'C5'))), ('ENGINEERING SCIENCE SUBJECTS', (('PHYSICS', 'PHYSICS'), ('MATHS', 'MATHS'), ('CHEMISTRY', 'CHEMISTRY'), ('ELECTRONICS', 'ELECTRONICS'), ('ELECTRICAL', 'ELECTRICAL'), ('GRAPHICS', 'GRAPHICS'), ('MECHANICS', 'MECHANICS')))], default='', max_length=150),
        ),
        migrations.CreateModel(
            name='IndInst2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_faculty', models.CharField(max_length=150)),
                ('name_of_company', models.CharField(max_length=256)),
                ('sector', models.CharField(max_length=256)),
                ('title_of_training', models.CharField(max_length=256)),
                ('outcome', models.TextField()),
                ('department', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='department.department')),
            ],
        ),
    ]
