# Generated by Django 3.1.2 on 2020-11-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0008_auto_20201104_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indinst5',
            name='name_of_company',
            field=models.CharField(max_length=250),
        ),
    ]
