# Generated by Django 3.1.2 on 2021-01-03 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0008_extracurr1_extracurr2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentresult',
            old_name='perct',
            new_name='percentage',
        ),
    ]
