# Generated by Django 3.1.2 on 2021-03-01 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0008_auto_20210301_1521'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtendedUser',
        ),
    ]
