# Generated by Django 3.1.2 on 2021-02-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0008_auto_20210224_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library1',
            name='books_Added_This_Month',
            field=models.PositiveIntegerField(verbose_name='Number of Books added This Month'),
        ),
        migrations.AlterField(
            model_name='library1',
            name='current_Periodicals',
            field=models.PositiveIntegerField(verbose_name='Current Periodicals'),
        ),
        migrations.AlterField(
            model_name='library1',
            name='month',
            field=models.CharField(choices=[('Jan', 'Jan'), ('Feb', 'HOD'), ('sadmin', 'sadmin'), ('teacher', 'teacher'), ('non-teach', 'non-teach')], default=2, max_length=150, unique=True, verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='library1',
            name='new_Books_Cost',
            field=models.PositiveIntegerField(verbose_name='Cost spent on new books This Month (Rs.)'),
        ),
        migrations.AlterField(
            model_name='library1',
            name='number_of_International_Journals',
            field=models.PositiveIntegerField(verbose_name='Number of International Journals'),
        ),
        migrations.AlterField(
            model_name='library1',
            name='number_of_National_Journals',
            field=models.PositiveIntegerField(verbose_name='Number of National Journals'),
        ),
        migrations.AlterField(
            model_name='library1',
            name='number_of_Volumes',
            field=models.PositiveIntegerField(verbose_name='Number of Volumes'),
        ),
        migrations.AlterField(
            model_name='library1',
            name='thesis_and_Dissertations',
            field=models.PositiveIntegerField(verbose_name='Thesis & Dissertations'),
        ),
        migrations.AlterField(
            model_name='library1',
            name='total_Books',
            field=models.PositiveIntegerField(verbose_name='Total Number of Books'),
        ),
        migrations.AlterField(
            model_name='library1',
            name='year',
            field=models.IntegerField(choices=[(2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], default=2021, unique=True, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='placement1',
            name='year',
            field=models.IntegerField(choices=[(2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], default=2021, unique=True, verbose_name='year'),
        ),
    ]
