# Generated by Django 3.1.2 on 2020-11-02 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0009_auto_20201102_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indinst2',
            name='department',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='department.department'),
        ),
        migrations.CreateModel(
            name='IndInst3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_faculty', models.CharField(max_length=150)),
                ('name_of_company', models.CharField(max_length=256)),
                ('sector', models.CharField(max_length=256)),
                ('title_of_training', models.CharField(max_length=256)),
                ('outcome', models.TextField()),
                ('department', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='department.department')),
            ],
        ),
    ]
