# Generated by Django 3.1.2 on 2021-01-06 01:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0009_auto_20210103_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResFunds2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funding_agency', models.CharField(max_length=150)),
                ('grants_recieved', models.IntegerField()),
                ('grants_utilized', models.IntegerField()),
                ('remaining_grant', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ResInternational3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('department', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Electronics and Telecommunication', 'Electronics and Telecommunication'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil')], default='Computer Science', max_length=150)),
                ('authors_name', models.CharField(max_length=150)),
                ('journal_name', models.CharField(max_length=150)),
                ('date_of_publication', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('amount', models.CharField(max_length=150, verbose_name='Amount (if paid by institute)')),
                ('volume', models.CharField(max_length=150, verbose_name='Volume, Issue, Page Number and Impact Factor/ICV')),
                ('approval', models.CharField(choices=[('', 'Choose...'), ('UGC', 'UGC'), ('SCOPUS', 'SCOPUS'), ('Web of Science', 'Web of Science'), ('Other', 'Other')], default='', max_length=150)),
                ('url', models.URLField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ResNational4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('department', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Electronics and Telecommunication', 'Electronics and Telecommunication'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil')], default='Computer Science', max_length=150)),
                ('authors_name', models.CharField(max_length=150)),
                ('journal_name', models.CharField(max_length=150)),
                ('date_of_publication', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('amount', models.CharField(max_length=150, verbose_name='Amount (if paid by institute)')),
                ('volume', models.CharField(max_length=150, verbose_name='Volume, Issue, Page Number and Impact Factor/ICV')),
                ('approval', models.CharField(choices=[('', 'Choose...'), ('UGC', 'UGC'), ('SCOPUS', 'SCOPUS'), ('Web of Science', 'Web of Science'), ('Other', 'Other')], default='', max_length=150)),
                ('url', models.URLField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ResProject1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('department', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Electronics and Telecommunication', 'Electronics and Telecommunication'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil')], default='Computer Science', max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField(default=datetime.date.today)),
                ('agency', models.CharField(max_length=150)),
                ('other', models.CharField(max_length=150)),
            ],
        ),
        migrations.RenameModel(
            old_name='IndInst4Model',
            new_name='IndInst4',
        ),
        migrations.AlterField(
            model_name='deptstartup6',
            name='website',
            field=models.URLField(max_length=150),
        ),
        migrations.AlterField(
            model_name='studfac2',
            name='type_of_self_learning_facility',
            field=models.CharField(choices=[('', 'Choose...'), ('Webinars', 'Webinars'), ('Podcast', 'Podcast'), ('MOOC’s', 'MOOC’s'), ('NPTEL courses', 'NPTEL courses'), ('Myexamo', 'Myexamo'), ('Others', 'Others')], default=1, max_length=150),
        ),
        migrations.AlterField(
            model_name='studfac3',
            name='name_of_competitive_exam_appeard_or_qualified',
            field=models.CharField(choices=[('', 'Choose...'), ('MPSC', 'MPSC'), ('UPSC', 'UPSC'), ('GATE', 'GATE'), ('GRE', 'GRE'), ('IELTS', 'IELTS'), ('TOEFL', 'TOEFL'), ('CAT', 'CAT'), ('Others', 'Others')], default=1, max_length=150),
        ),
        migrations.AlterField(
            model_name='studfac4',
            name='name_of_activity',
            field=models.CharField(choices=[('', 'Choose...'), ('Soft Skill Development', 'Soft Skill Development'), ('Remedial Coaching', 'Remedial Coaching'), ('Language Lab', 'Language Lab'), ('Yoga', 'Yoga'), ('Meditation', 'Meditation'), ('Personal Counseling', 'Personal Counseling'), ('Bridge Courses', 'Bridge Courses'), ('Competitive Examination', 'Competitive Examination'), ('Higher', 'Higher')], default=1, max_length=150),
        ),
    ]
