# Generated by Django 3.1.2 on 2021-03-13 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0010_auto_20210311_2156'),
        ('department', '0010_auto_20210312_1112'),
    ]

    operations = [
    ]
