# Generated by Django 2.2.16 on 2020-11-03 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('department', '0010_auto_20201102_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField(blank=True, choices=[('admin', 'admin'), ('HOD', 'HOD'), ('sadmin', 'sadmin'), ('teacher', 'teacher'), ('non-teach', 'non-teach')], default='non-teach', max_length=10)),
                ('dept', models.CharField(blank=True, choices=[('ALLD', 'ALLD'), ('COMP', 'COMP'), ('ENTC', 'ENTC'), ('MECH', 'MECH'), ('CIVI', 'CIVI'), ('VIEW', 'VIEW')], default='VIEW', max_length=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
